hydra:
  job:
    chdir: true
  run:
    dir: outputs/default/${hydra.job.override_dirname}
  sweep:
    dir: outputs/default
    subdir: ${hydra.job.override_dirname}

seed: 0 # random seed
n_trials: 20 # number of trials
bs: 1 # batch size
step: 500 # number of steps
n_actions: 50 # number of actions(number of arms)
dim_context: 10 # dimension of context
dim_action_context: 15 # dimension of action context
task_type: "regression" # regression or classification
